image: ubuntu:15.10

stages:
  - build

before_script:
  - apt-get update
  - apt-get install -y --force-yes --no-install-recommends openjdk-8-jdk scala 

build:
  stage: build
  script:
    - ./gradlew build
